### ISSUE TITLE
RepoConfig path is not clear or redundant

### ISSUE THREAD

**Issue by HDouss** [artipie/artipie#82]
RepoConfig class has a `path` method. The implementation reads the yaml setting repo.path in the repo file setting.
First, it is not documented at all that the repo file settings could have an entry like repo -> path.
Second, I am not sure if that is redundant with repo -> storage -> path, in which case, the method should just disappear.
Finally, the only usage of this method is when building PhpComposer (in Pie class). Looking at the usage of this data in PhpComposer makes me wonder what this "base" is for, it is only used to check if the incoming request has that "base" as a prefix.
Whether there is some sort of a bug or there is a clear lack of documentation: at least what is a "base path" for PhpComposer slice, and how it is different from its storage path.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by HDouss** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@HDouss I think `path` for `PhpComposer` should be moved to `settings` introduced in https://github.com/artipie/artipie/pull/80
`storage` **may** have a path in case if it's file system storage. In this case path means the location of directory in file system

**Comment by olegmoz** [comment]
@HDouss @g4s8  `path` is base HTTP path for given `Pie`. Right now we have only one `Pie` per host, but I believe that our intent is to have multiple repositories on single host. `path` setting is not related in any way to storage configuration, it's about HTTP path to repository.

**Comment by 0crat** [comment]
The job [#82](https://github.com/artipie/artipie/issues/82) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9b1138e2-46b0-46ff-8460-a0fcaf4faff4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@olegmoz I suppose it's already working as you say: we can configure multiple repositories on one host, we use the same path structure as Artifactory uses: first part of URI path is repository name, e.g. `artipie.com/central/com/artipie/http/1.0` URI means that it's requesting some content from `artipie.com` from `central` repository with `com/artipie/http/1.0` resource id. So we're using first part of path to understand what `Slice` is responsible to handle HTTP request.

**Comment by olegmoz** [comment]
@g4s8 oh, didn't know that. How it is supposed to work for Docker then? It's path cannot be prefixed with anything, it has to be `/v2/<custom name>/...` as far as I know. I think we discussed before that full path should be forwarded to adapter's slice and it's adapter's job to cut it out.

**Comment by olegmoz** [comment]
@g4s8 so I believe that we decide that path prefix is to be managed by each adapter in it's own way. So this issue may be closed?

**Comment by HDouss** [comment]
@olegmoz The issue is about RepoConfig exposing a path method that is either useless, or not documented at all. At least, there is no documentation or usage for the yaml setting (repo -> path), to not be confused with repo -> storage -> path.

**Comment by g4s8** [comment]
@olegmoz it seems Artifactory uses custom registry path for Dockers, see: https://www.jfrog.com/confluence/display/JFROG/Docker+Registry

> When accessing a remote Docker repository through Artifactory, the repository URL must be > prefixed with api/docker in the path.
>
> For Example:
> 
> http://my-remote-site:8081/artifactory/api/docker/<repository key>

**Comment by olegmoz** [comment]
@g4s8 could we close this issue as there is issue #185 ?

**Comment by g4s8** [comment]
@olegmoz yes, closing.
